---
- name: nginx install
  become: yes
  apt:
    name: "{{item}}"
  with_items:
    - nginx

- name: rename original nginx.conf
  become: yes
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org

- name: mk nginx cert
  become: yes
  shell: mkdir -p /etc/nginx/cert

- name: create ssl cert and ssl key
  become: yes
  shell: sudo openssl req -new -days 3650 -x509 -nodes -keyout /etc/nginx/cert/ssl.key -out /etc/nginx/cert/ssl.crt

- name: deploy nginx conf
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf