---

- name: Add gdrive Repository
  become: yes
  shell: add-apt-repository ppa:alessandro-strada/ppa

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: apt install
  become: yes
  apt:
    name: "{{item}}"
  with_items: "{{apt_packages}}"
