---
- name: apt repository
  become: yes
  apt_repository:
    repo: "{{item}}"
  with_items: "{{apt_repos}}"

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: apt install
  become: yes
  apt:
    name: "{{item}}"
  with_items: "{{apt_packages}}"
