---
apt_packages:
  - tmux
  - language-pack-ja-base
  - language-pack-ja
  - ibus-mozc
  - lv
  - emacs
  - rlwrap
  - gnupg
  - emacs-mozc
  - gdebi-core
  - nginx
  - tree
  - golang
  - google-drive-ocamlfuse

apt_repos:
  - ppa:webupd8team/java
  - ppa:alessandro-strada/ppa